---
# Source: dragonfly/charts/mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-mysql
  namespace: "dragonfly-system"
  labels:
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.36
    helm.sh/chart: mysql-10.1.1
type: Opaque
data:
  mysql-root-password: "ZHJhZ29uZmx5LXJvb3Q="
  mysql-password: "ZHJhZ29uZmx5"
