---
# Source: dragonfly/charts/mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dragonfly-mysql
  namespace: "dragonfly-system"
  labels:
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: 8.0.36
    helm.sh/chart: mysql-10.1.1
automountServiceAccountToken: false
secrets:
  - name: dragonfly-mysql
