---
# Source: cockroachdb/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cockroachdb-release-auth
  namespace: "auth"
  labels:
    helm.sh/chart: cockroachdb-14.0.5
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb-release"
    app.kubernetes.io/managed-by: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cockroachdb-release-auth
subjects:
  - kind: ServiceAccount
    name: cockroachdb-release
    namespace: "auth"
