---
# Source: cockroachdb/templates/role-certSelfSigner.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cockroachdb-release-self-signer
  namespace: "auth"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    helm.sh/chart: cockroachdb-14.0.5
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb-release"
    app.kubernetes.io/managed-by: "Helm"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
    resourceNames:
      - cockroachdb-release
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get"]
