---
# Source: cockroachdb/templates/serviceaccount-certRotateSelfSigner.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cockroachdb-rotate-self-signer
  namespace: "cockroachdb-system"
  labels:
    helm.sh/chart: cockroachdb-16.0.6
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"
    app.kubernetes.io/managed-by: "Helm"
