---
# Source: cockroachdb/templates/serviceaccount-certRotateSelfSigner.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cockroachdb-release-rotate-self-signer
  namespace: "auth"
  labels:
    helm.sh/chart: cockroachdb-14.0.5
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb-release"
    app.kubernetes.io/managed-by: "Helm"
