---
# Source: logstash/templates/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "logstash-release-logstash-pdb"
  labels:
    app: "logstash-release-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash-release"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "logstash-release-logstash"
