---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-release-filebeat-cluster-role-binding
  labels:
    app: "filebeat-release-filebeat"
    chart: "filebeat-8.5.1"
    heritage: "Helm"
    release: "filebeat-release"
roleRef:
  kind: ClusterRole
  name: filebeat-release-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-release-filebeat
  namespace: monitoring
