---
# Source: filebeat/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-release-filebeat-daemonset-config
  labels:
    app: "filebeat-release-filebeat"
    chart: "filebeat-8.5.1"
    heritage: "Helm"
    release: "filebeat-release"
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
    
    output.logstash:
      hosts: ["logstash-logstash:5044"]
