apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - configmap.yaml
  - daemonset.yaml
  - deployment.yaml
  - kustomization.yaml
  - rolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
