services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.2
    volumes:
      - ./data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER = elastic
      - ELASTIC_PASSWORD = Re4=aPR5C5z-qb*9hGFr
      - ELASTIC_HOSTS = http://elasticsearch:9200
    # ports:
    #   - "5044:5044"
    networks:
      - elknet