services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.2
    volumes:
      - ./data/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - "5044:5044"
    networks:
      - elknet