apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/poddisruptionbudget.yaml
  - templates/secret-cert.yaml
  - templates/secret.yaml
  - templates/service.yaml
  - templates/statefulset.yaml
  - templates/test/test-elasticsearch-health.yaml
