apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/configmap-helm-scripts.yaml
  - templates/deployment.yaml
  - templates/post-delete-job.yaml
  - templates/post-delete-rolebinding.yaml
  - templates/post-delete-role.yaml
  - templates/post-delete-serviceaccount.yaml
  - templates/pre-install-job.yaml
  - templates/pre-install-rolebinding.yaml
  - templates/pre-install-role.yaml
  - templates/pre-install-serviceaccount.yaml
  - templates/service.yaml
