---
# Source: dragonfly/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-redis
  namespace: "dragonfly-system"
  labels:
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.5
    helm.sh/chart: redis-19.5.5
type: Opaque
data:
  redis-password: "ZHJhZ29uZmx5"
