apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zitadel/templates/configmap.yaml
  - zitadel/templates/deployment.yaml
  - zitadel/templates/initjob.yaml
  - zitadel/templates/secret_zitadel-masterkey.yaml
  - zitadel/templates/secret_zitadel-secrets.yaml
  - zitadel/templates/serviceaccount.yaml
  - zitadel/templates/service.yaml
  - zitadel/templates/setupjob.yaml
