---
# Source: rabbitmq-cluster-operator/templates/messaging-topology-operator/aggregate-cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-release-rabbitmq-messaging-topology-operator-bus-admin
  labels:
    app.kubernetes.io/instance: rabbit-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.26
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings
      - exchanges
      - federations
      - operatorpolicies
      - permissions
      - policies
      - queues
      - schemareplications
      - shovels
      - superstreams
      - topicpermissions
      - users
      - vhosts
    verbs: 
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
# Source: rabbitmq-cluster-operator/templates/messaging-topology-operator/aggregate-cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-release-rabbitmq-messaging-topology-operator-bus-edit
  labels:
    app.kubernetes.io/instance: rabbit-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.26
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings
      - exchanges
      - federations
      - operatorpolicies
      - permissions
      - policies
      - queues
      - schemareplications
      - shovels
      - superstreams
      - topicpermissions
      - users
      - vhosts
    verbs: 
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
---
# Source: rabbitmq-cluster-operator/templates/messaging-topology-operator/aggregate-cluster-roles.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbit-release-rabbitmq-messaging-topology-operator-bus-view
  labels:
    app.kubernetes.io/instance: rabbit-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.26
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - rabbitmq.com
    resources:
      - bindings
      - exchanges
      - federations
      - operatorpolicies
      - permissions
      - policies
      - queues
      - schemareplications
      - shovels
      - superstreams
      - topicpermissions
      - users
      - vhosts
    verbs: 
      - get
      - list
      - watch
