---
# Source: rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rabbit-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 2.11.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.26
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbit-release-rabbitmq-messaging-topology-operator-bus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit-release-rabbitmq-messaging-topology-operator-bus
subjects:
  - kind: ServiceAccount
    name: rabbit-release-rabbitmq-messaging-topology-operator
    namespace: "bus"
