---
# Source: rabbitmq-cluster-operator/templates/messaging-topology-operator/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rabbit-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/version: 1.15.0
    helm.sh/chart: rabbitmq-cluster-operator-4.3.26
    app.kubernetes.io/component: messaging-topology-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbit-release-rabbitmq-messaging-topology-operator
  namespace: "bus"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbit-release-rabbitmq-messaging-topology-operator
subjects:
  - kind: ServiceAccount
    name: rabbit-release-rabbitmq-messaging-topology-operator
    namespace: "bus"
