include:
  - net.yaml
  - storage.yaml

services:
  rabbit-lb:
    image: haproxy:latest
    restart: always
    container_name: rabbit-lb
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - rabbitnet

  rabbitmq1:
    image: rabbitmq:3.11-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_VHOST: '/'
    networks:
      - rabbitnet
    entrypoint: ['sh', '/usr/local/bin/cluster-entrypoint.sh']
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

  rabbitmq2:
    image: rabbitmq:3.11-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_VHOST: '/'
      JOIN_CLUSTER_HOST: rabbitmq1
    depends_on:
      - rabbitmq1
    networks:
      - rabbitnet
    entrypoint: ['sh', '/usr/local/bin/cluster-entrypoint.sh']
    volumes:
      - rabbit2:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

  rabbitmq3:
    image: rabbitmq:3.11-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      RABBITMQ_ERLANG_COOKIE: 'mysecretcookie'
      RABBITMQ_DEFAULT_USER: 'admin'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_VHOST: '/'
      JOIN_CLUSTER_HOST: rabbitmq1
    depends_on:
      - rabbitmq1
      - rabbitmq2
    networks:
      - rabbitnet
    entrypoint: ['sh', '/usr/local/bin/cluster-entrypoint.sh']
    volumes:
      - rabbit3:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh

