---
# Source: zitadel/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-yaml
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    helm.sh/chart: zitadel-8.5.0
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel-release
    app.kubernetes.io/version: "v2.61.0"
    app.kubernetes.io/managed-by: Helm
data:
  zitadel-config-yaml: |-
    
    Database:
      Cockroach:
        Admin:
          SSL:
            Mode: verify-full
        Host: db-cockroachdb-public
        User:
          SSL:
            Mode: verify-full
    ExternalDomain: 127.0.0.1.sslip.io
    ExternalSecure: false
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    TLS:
      Enabled: false
