---
# Source: zitadel/templates/secret_zitadel-secrets.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-secrets-yaml
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    helm.sh/chart: zitadel-8.5.0
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel-release
    app.kubernetes.io/version: "v2.61.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  zitadel-secrets-yaml: |-
    
    Database:
      Cockroach:
        Admin:
          Password: abc
        User:
          Password: xyz
