---
# Source: zitadel/templates/secret_zitadel-masterkey.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: zitadel-masterkey
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
  labels:
    helm.sh/chart: zitadel-8.5.0
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel-release
    app.kubernetes.io/version: "v2.61.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  masterkey: x123456789012345678901234567891y
