services:
  gateway:
    image: haproxy:latest
    restart: always
    ports:
      - 80:80
      - 8001:8001
      - 5601:5601
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - usnet
      - elknet
      - authnet
